version: "3"
services:
  nodeocr:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/app/src
    ports:
      - 3000:3000
    environment:
      - IMAGE_UPLOAD_PATH=./public/upload/image
      - TEXT_UPLOAD_PATH=./public/upload/text
